spring.application.name=SpringSec

spring.security.user.name=hamza
spring.security.user.password=sbihi

spring.datasource.url=jdbc:postgresql://localhost:5432/karijad
spring.datasource.username=postgres
spring.datasource.password=user
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

